

myNextApplication:
  component: "@sls-next/serverless-component@latest"
  inputs:
    domain: ["meeting-room", "play.kurlycorp.com"]
    name:
      defaultLambda: "kmr-default-lambda"
      apiLambda: "kmr-api-lambda"
    bucketName: "kurly-meeting-room-2"
    bucketRegion: "ap-northeast-2"
    cloudfront:
      distributionId: "EB30MPOJNCWYQ"
      comment: 'kurly-meeting-room deploy'
    plugins: ["serverless-s3-remover"]
    custom:
      remover:
        buckets: ["kurly-meeting-room-2"]


